version: 0.2
phases:
  pre_build:
    commands:
      - echo "This is a test"
  build:
    commands:
      - echo "Running all unit tests"
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'