# Generated by Django 3.2.11 on 2022-02-07 22:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('status_changed', model_utils.fields.MonitorField(default=django.utils.timezone.now, monitor='status', verbose_name='status changed')),
                ('status', models.CharField(choices=[('D', 'draft'), ('P', 'published')], default='D', max_length=1)),
                ('post_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('title_sub_text', models.CharField(blank=True, max_length=200)),
                ('subtitle1', models.CharField(max_length=50)),
                ('text1', models.TextField()),
                ('subtitle2', models.CharField(blank=True, max_length=50)),
                ('text2', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='blog/posts/')),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blog/posts/')),
                ('image1_title', models.CharField(blank=True, max_length=50)),
                ('image1_text', models.CharField(blank=True, max_length=200)),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog/posts/')),
                ('image2_title', models.CharField(blank=True, max_length=50)),
                ('image2_text', models.CharField(blank=True, max_length=200)),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blog/posts/')),
                ('image3_title', models.CharField(blank=True, max_length=50)),
                ('image3_text', models.CharField(blank=True, max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
